#!/bin/zsh

exitfn () {
    trap SIGINT
    echo; echo 'Aarghh!!'
    docker-compose down
    exit
}

trap "exitfn" INT            # Set up SIGINT trap to call function.


docker-compose build
docker-compose up

